'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel.DataAnnotations

Partial Public Class car
    Public Property id As Integer
    <Required>
    Public Property Marca As String
    Public Property Modelo As String
    Public Property Precio As Decimal
    Public Property Motor As String
    Public Property Año As Decimal
    Public Property Kilometraje As Decimal
    Public Property Combustion As Integer
    Public Property Marchas As Integer
    Public Property Localidad As String

    Public Overridable Property enum_fuel As enum_fuel
    Public Overridable Property enum_gearbox As enum_gearbox

End Class
