'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cars
    Public Property id As Integer
    Public Property brand As String
    Public Property model As String
    Public Property price As Nullable(Of Decimal)
    Public Property engine As String
    Public Property year As Nullable(Of Decimal)
    Public Property mileage As Nullable(Of Decimal)
    Public Property fuel As Nullable(Of Integer)
    Public Property gearbox As Nullable(Of Integer)
    Public Property location As String

End Class
