'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class ConcesionarioEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ConcesionarioEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property cars() As DbSet(Of cars)
    Public Property enum_fuel() As DbSet(Of enum_fuel)
    Public Property enum_gearbox() As DbSet(Of enum_gearbox)

End Class
